from Core.SearchTree import SearchTree
from Core.TreeCreator import TreeCreator

if __name__ == "__main__":
    searchTree = SearchTree()
    treeCreator = TreeCreator()
    treeCreator.create_tree(searchTree.currentNode)
    print(searchTree.currentNode.children)
    print(searchTree.get_game_state())
    print(searchTree.currentNode.playerType)
    # searchTree.make_move(5)
    searchTree.make_optimal_move()
    print(searchTree.currentNode.children)
    print(searchTree.get_game_state())
    print(searchTree.currentNode.playerType)
    # searchTree.make_move(9)
    searchTree.make_optimal_move()
    print(searchTree.currentNode.children)
    print(searchTree.get_game_state())
    print(searchTree.currentNode.playerType)
    # searchTree.make_move(1)
    searchTree.make_optimal_move()
    print(searchTree.currentNode.children)
    print(searchTree.get_game_state())
    print(searchTree.currentNode.playerType)
